INSERT INTO icons (name, category, object_key) VALUES ('AWS Elastic Beanstalk', 'Compute', 'compute/Arch_AWS-Elastic-Beanstalk_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Thinkbox XMesh', 'Compute', 'compute/Arch_AWS-Thinkbox-XMesh_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Nitro Enclaves', 'Compute', 'compute/Arch_AWS-Nitro-Enclaves_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Thinkbox Stoke', 'Compute', 'compute/Arch_AWS-Thinkbox-Stoke_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Thinkbox Frost', 'Compute', 'compute/Arch_AWS-Thinkbox-Frost_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Bottlerocket', 'Compute', 'compute/Arch_Bottlerocket_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lightsail for Research', 'Compute', 'compute/Arch_Amazon-Lightsail-for-Research_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Outposts rack', 'Compute', 'compute/Arch_AWS-Outposts-rack_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Outposts servers', 'Compute', 'compute/Arch_AWS-Outposts-servers_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lightsail', 'Compute', 'compute/Arch_Amazon-Lightsail_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Outposts family', 'Compute', 'compute/Arch_AWS-Outposts-family_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS App Runner', 'Compute', 'compute/Arch_AWS-App-Runner_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Compute Optimizer', 'Compute', 'compute/Arch_AWS-Compute-Optimizer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS SimSpace Weaver', 'Compute', 'compute/Arch_AWS-SimSpace-Weaver_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Thinkbox Deadline', 'Compute', 'compute/Arch_AWS-Thinkbox-Deadline_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('VMware Cloud on AWS', 'Compute', 'compute/Arch_VMware-Cloud-on-AWS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Serverless Application Repository', 'Compute', 'compute/Arch_AWS-Serverless-Application-Repository_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EC2 Image Builder', 'Compute', 'compute/Arch_Amazon-EC2-Image-Builder_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('NICE EnginFrame', 'Compute', 'compute/Arch_NICE-EnginFrame_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Local Zones', 'Compute', 'compute/Arch_AWS-Local-Zones_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Thinkbox Sequoia', 'Compute', 'compute/Arch_AWS-Thinkbox-Sequoia_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Reserved Instance Reporting', 'Compute', 'compute/Arch_AWS-Parallel-Cluster_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Savings Plans', 'Compute', 'compute/Arch_Amazon-EC2-Auto-Scaling_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Billing Conductor', 'Compute', 'compute/Arch_NICE-DCV_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Cost Profiler', 'Compute', 'compute/Arch_Elastic-Fabric-Adapter_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Budgets', 'Compute', 'compute/Arch_AWS-Lambda_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cost and Usage Report', 'Compute', 'compute/Arch_AWS-Wavelength_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cost Explorer', 'Compute', 'compute/Arch_AWS-Thinkbox-Krakatoa_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Genomics CLI', 'Compute', 'compute/Arch_Amazon-Genomics-CLI_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Batch', 'Compute', 'compute/Arch_AWS-Batch_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cloud Map', 'Network', 'network/Arch_AWS-Cloud-Map_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Global Accelerator', 'Network', 'network/Arch_AWS-Global-Accelerator_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS App Mesh', 'Network', 'network/Arch_AWS-App-Mesh_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Direct Connect', 'Network', 'network/Arch_AWS-Direct-Connect_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Route 53', 'Network', 'network/Arch_Amazon-Route-53_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Client VPN', 'Network', 'network/Arch_AWS-Client-VPN_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CloudFront', 'Network', 'network/Arch_Amazon-CloudFront_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Private 5G', 'Network', 'network/Arch_AWS-Private-5G_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Site to Site VPN', 'Network', 'network/Arch_AWS-Site-to-Site-VPN_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Virtual Private Cloud', 'Network', 'network/Arch_Amazon-Virtual-Private-Cloud_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon VPC Lattice', 'Network', 'network/Arch_Amazon-VPC-Lattice_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Elastic Load Balancing', 'Network', 'network/Arch_Elastic-Load-Balancing_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Verified Access', 'Network', 'network/Arch_AWS-Verified-Access_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cloud WAN', 'Network', 'network/Arch_AWS-Cloud-WAN_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Transit Gateway', 'Network', 'network/Arch_AWS-Transit-Gateway_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS PrivateLink', 'Network', 'network/Arch_AWS-PrivateLink_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon RDS on VMware', 'Database', 'database/Arch_Amazon-RDS-on-VMware_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon DocumentDB', 'Database', 'database/Arch_Amazon-DocumentDB_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Database Migration Service', 'Database', 'database/Arch_AWS-Database-Migration-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon MemoryDB for Redis', 'Database', 'database/Arch_Amazon-MemoryDB-for-Redis_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon ElastiCache', 'Database', 'database/Arch_Amazon-ElastiCache_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Timestream', 'Database', 'database/Arch_Amazon-Timestream_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon DynamoDB', 'Database', 'database/Arch_Amazon-DynamoDB_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Aurora', 'Database', 'database/Arch_Amazon-Aurora_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Keyspaces', 'Database', 'database/Arch_Amazon-Keyspaces_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Neptune', 'Database', 'database/Arch_Amazon-Neptune_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon RDS', 'Database', 'database/Arch_Amazon-RDS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Storage Gateway', 'Storage', 'storage/Arch_AWS-Storage-Gateway_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon File Cache', 'Storage', 'storage/Arch_Amazon-File-Cache_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Backup', 'Storage', 'storage/Arch_AWS-Backup_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Block Store', 'Storage', 'storage/Arch_Amazon-Elastic-Block-Store_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FSx for WFS', 'Storage', 'storage/Arch_Amazon-FSx-for-WFS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FSx', 'Storage', 'storage/Arch_Amazon-FSx_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Snowball', 'Storage', 'storage/Arch_AWS-Snowball_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FSx for OpenZFS', 'Storage', 'storage/Arch_Amazon-FSx-for-OpenZFS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FSx for NetApp ONTAP', 'Storage', 'storage/Arch_Amazon-FSx-for-NetApp-ONTAP_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FSx for Lustre', 'Storage', 'storage/Arch_Amazon-FSx-for-Lustre_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon S3 on Outposts', 'Storage', 'storage/Arch_Amazon-S3-on-Outposts_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Simple Storage Service', 'Storage', 'storage/Arch_Amazon-Simple-Storage-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Snowcone', 'Storage', 'storage/Arch_AWS-Snowcone_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Snowball Edge', 'Storage', 'storage/Arch_AWS-Snowball-Edge_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EFS', 'Storage', 'storage/Arch_Amazon-EFS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Snowmobile', 'Storage', 'storage/Arch_AWS-Snowmobile_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elastic Disaster Recovery', 'Storage', 'storage/Arch_AWS-Elastic-Disaster-Recovery_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Simple Storage Service Glacier', 'Storage', 'storage/Arch_Amazon-Simple-Storage-Service-Glacier_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Kubernetes Service', 'Container', 'container/Arch_Amazon-Elastic-Kubernetes-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Container Registry', 'Container', 'container/Arch_Amazon-Elastic-Container-Registry_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Red Hat OpenShift Service on AWS', 'Container', 'container/Arch_Red-Hat-OpenShift-Service-on-AWS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EKS Anywhere', 'Container', 'container/Arch_Amazon-EKS-Anywhere_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Fargate', 'Container', 'container/Arch_AWS-Fargate_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Container Service', 'Container', 'container/Arch_Amazon-Elastic-Container-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EKS Cloud', 'Container', 'container/Arch_Amazon-EKS-Cloud_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EKS Distro', 'Container', 'container/Arch_Amazon-EKS-Distro_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon ECS Anywhere', 'Container', 'container/Arch_Amazon-ECS-Anywhere_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis Data Streams', 'Analytics', 'analytics/Arch_Amazon-Kinesis-Data-Streams_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis Data Firehose', 'Analytics', 'analytics/Arch_Amazon-Kinesis-Data-Firehose_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Glue', 'Analytics', 'analytics/Arch_AWS-Glue_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Managed Streaming for Apache Kafka', 'Analytics', 'analytics/Arch_Amazon-Managed-Streaming-for-Apache-Kafka_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis Video Streams', 'Analytics', 'analytics/Arch_Amazon-Kinesis-Video-Streams_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Glue Elastic Views', 'Analytics', 'analytics/Arch_AWS-Glue-Elastic-Views_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon FinSpace', 'Analytics', 'analytics/Arch_Amazon-FinSpace_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Redshift', 'Analytics', 'analytics/Arch_Amazon-Redshift_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Data Exchange', 'Analytics', 'analytics/Arch_AWS-Data-Exchange_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon QuickSight', 'Analytics', 'analytics/Arch_Amazon-QuickSight_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CloudSearch', 'Analytics', 'analytics/Arch_Amazon-CloudSearch_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis', 'Analytics', 'analytics/Arch_Amazon-Kinesis_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Athena', 'Analytics', 'analytics/Arch_Amazon-Athena_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Data Pipeline', 'Analytics', 'analytics/Arch_AWS-Data-Pipeline_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon DataZone', 'Analytics', 'analytics/Arch_Amazon-DataZone_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Lake Formation', 'Analytics', 'analytics/Arch_AWS-Lake-Formation_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis Data Analytics', 'Analytics', 'analytics/Arch_Amazon-Kinesis-Data-Analytics_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Clean Rooms', 'Analytics', 'analytics/Arch_AWS-Clean-Rooms_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon OpenSearch Service', 'Analytics', 'analytics/Arch_Amazon-OpenSearch-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EMR', 'Analytics', 'analytics/Arch_Amazon-EMR_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Glue DataBrew', 'Analytics', 'analytics/Arch_AWS-Glue-DataBrew_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Identity and Access Management', 'Security', 'security/Arch_AWS-Identity-and-Access-Management_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Artifact', 'Security', 'security/Arch_AWS-Artifact_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Signer', 'Security', 'security/Arch_AWS-Signer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Network Firewall', 'Security', 'security/Arch_AWS-Network-Firewall_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Directory Service', 'Security', 'security/Arch_AWS-Directory-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Certificate Manager', 'Security', 'security/Arch_AWS-Certificate-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Shield', 'Security', 'security/Arch_AWS-Shield_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS WAF', 'Security', 'security/Arch_AWS-WAF_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon GuardDuty', 'Security', 'security/Arch_Amazon-GuardDuty_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Audit Manager', 'Security', 'security/Arch_AWS-Audit-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Verified Permissions', 'Security', 'security/Arch_Amazon-Verified-Permissions_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Macie', 'Security', 'security/Arch_Amazon-Macie_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Firewall Manager', 'Security', 'security/Arch_AWS-Firewall-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Inspector', 'Security', 'security/Arch_Amazon-Inspector_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Secrets Manager', 'Security', 'security/Arch_AWS-Secrets-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Resource Access Manager', 'Security', 'security/Arch_AWS-Resource-Access-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Security Lake', 'Security', 'security/Arch_Amazon-Security-Lake_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Cognito', 'Security', 'security/Arch_Amazon-Cognito_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Key Management Service', 'Security', 'security/Arch_AWS-Key-Management-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IAM Identity Center', 'Security', 'security/Arch_AWS-IAM-Identity-Center_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Private Certificate Authority', 'Security', 'security/Arch_AWS-Private-Certificate-Authority_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Security Hub', 'Security', 'security/Arch_AWS-Security-Hub_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Cloud Directory', 'Security', 'security/Arch_Amazon-Cloud-Directory_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Detective', 'Security', 'security/Arch_Amazon-Detective_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CloudHSM', 'Security', 'security/Arch_AWS-CloudHSM_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cloud Control API', 'Developer Tools', 'developer_tools/Arch_AWS-Cloud-Control-API_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Corretto', 'Developer Tools', 'developer_tools/Arch_Amazon-Corretto_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cloud Development Kit', 'Developer Tools', 'developer_tools/Arch_AWS-Cloud-Development-Kit_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodeCommit', 'Developer Tools', 'developer_tools/Arch_AWS-CodeCommit_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cloud9', 'Developer Tools', 'developer_tools/Arch_AWS-Cloud9_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodeDeploy', 'Developer Tools', 'developer_tools/Arch_AWS-CodeDeploy_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CodeCatalyst', 'Developer Tools', 'developer_tools/Arch_Amazon-CodeCatalyst_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CloudShell', 'Developer Tools', 'developer_tools/Arch_AWS-CloudShell_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Composer', 'Developer Tools', 'developer_tools/Arch_AWS-Application-Composer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Tools and SDKs', 'Developer Tools', 'developer_tools/Arch_AWS-Tools-and-SDKs_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodeArtifact', 'Developer Tools', 'developer_tools/Arch_AWS-CodeArtifact_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS X Ray', 'Developer Tools', 'developer_tools/Arch_AWS-X-Ray_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Command Line Interface', 'Developer Tools', 'developer_tools/Arch_AWS-Command-Line-Interface_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodeBuild', 'Developer Tools', 'developer_tools/Arch_AWS-CodeBuild_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodeStar', 'Developer Tools', 'developer_tools/Arch_AWS-CodeStar_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CodePipeline', 'Developer Tools', 'developer_tools/Arch_AWS-CodePipeline_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Distro for OpenTelemetry', 'Management Governance', 'management_governance/Arch_AWS-Distro-for-OpenTelemetry_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Chatbot', 'Management Governance', 'management_governance/Arch_AWS-Chatbot_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CloudFormation', 'Management Governance', 'management_governance/Arch_AWS-CloudFormation_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Backint Agent', 'Management Governance', 'management_governance/Arch_AWS-Backint-Agent_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS CloudTrail', 'Management Governance', 'management_governance/Arch_AWS-CloudTrail_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Proton', 'Management Governance', 'management_governance/Arch_AWS-Proton_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Well Architected Tool', 'Management Governance', 'management_governance/Arch_AWS-Well-Architected-Tool_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Resilience Hub', 'Management Governance', 'management_governance/Arch_AWS-Resilience-Hub_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Resource Explorer', 'Management Governance', 'management_governance/Arch_AWS-Resource-Explorer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Service Catalog', 'Management Governance', 'management_governance/Arch_AWS-Service-Catalog_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Health Dashboard', 'Management Governance', 'management_governance/Arch_AWS-Health-Dashboard_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Auto Scaling', 'Management Governance', 'management_governance/Arch_AWS-Auto-Scaling_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Management Console', 'Management Governance', 'management_governance/Arch_AWS-Management-Console_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Control Tower', 'Management Governance', 'management_governance/Arch_AWS-Control-Tower_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Trusted Advisor', 'Management Governance', 'management_governance/Arch_AWS-Trusted-Advisor_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Telco Network Builder', 'Management Governance', 'management_governance/Arch_AWS-Telco-Network-Builder_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Auto Scaling', 'Management Governance', 'management_governance/Arch_AWS-Application-Auto-Scaling_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Systems Manager', 'Management Governance', 'management_governance/Arch_AWS-Systems-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Launch Wizard', 'Management Governance', 'management_governance/Arch_AWS-Launch-Wizard_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS License Manager', 'Management Governance', 'management_governance/Arch_AWS-License-Manager_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Organizations', 'Management Governance', 'management_governance/Arch_AWS-Organizations_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CloudWatch', 'Management Governance', 'management_governance/Arch_Amazon-CloudWatch_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Fault Injection Simulator', 'Management Governance', 'management_governance/Arch_AWS-Fault-Injection-Simulator_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS OpsWorks', 'Management Governance', 'management_governance/Arch_AWS-OpsWorks_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Managed Service for Prometheus', 'Management Governance', 'management_governance/Arch_Amazon-Managed-Service-for-Prometheus_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Managed Grafana', 'Management Governance', 'management_governance/Arch_Amazon-Managed-Grafana_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Service Management Connector', 'Management Governance', 'management_governance/Arch_AWS-Service-Management-Connector_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS AppConfig', 'Management Governance', 'management_governance/Arch_AWS-AppConfig_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Config', 'Management Governance', 'management_governance/Arch_AWS-Config_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon API Gateway', 'App Integration', 'app_integration/Arch_Amazon-API-Gateway_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Managed Workflows for Apache Airflow', 'App Integration', 'app_integration/Arch_Amazon-Managed-Workflows-for-Apache-Airflow_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS AppSync', 'App Integration', 'app_integration/Arch_AWS-AppSync_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon EventBridge', 'App Integration', 'app_integration/Arch_Amazon-EventBridge_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Step Functions', 'App Integration', 'app_integration/Arch_AWS-Step-Functions_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Console Mobile Application', 'App Integration', 'app_integration/Arch_AWS-Console-Mobile-Application_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Simple Notification Service', 'App Integration', 'app_integration/Arch_Amazon-Simple-Notification-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Simple Queue Service', 'App Integration', 'app_integration/Arch_Amazon-Simple-Queue-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Express Workflows', 'App Integration', 'app_integration/Arch_AWS-Express-Workflows_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon AppFlow', 'App Integration', 'app_integration/Arch_Amazon-AppFlow_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon MQ', 'App Integration', 'app_integration/Arch_Amazon-MQ_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaTailor', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaTailor_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kinesis Video Streams', 'Media Service', 'media_service/Arch_Amazon-Kinesis-Video-Streams_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaConnect', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaConnect_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Nimble Studio', 'Media Service', 'media_service/Arch_Amazon-Nimble-Studio_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaStore', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaStore_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Transcoder', 'Media Service', 'media_service/Arch_Amazon-Elastic-Transcoder_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaLive', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaLive_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaConvert', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaConvert_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Interactive Video Service', 'Media Service', 'media_service/Arch_Amazon-Interactive-Video-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental MediaPackage', 'Media Service', 'media_service/Arch_AWS-Elemental-MediaPackage_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Elemental Link', 'Media Service', 'media_service/Arch_AWS-Elemental-Link_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS GameKit', 'Games', 'games/Arch_AWS-GameKit_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon GameSparks', 'Games', 'games/Arch_Amazon-GameSparks_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Open 3D Engine', 'Games', 'games/Arch_Open-3D-Engine_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon GameLift', 'Games', 'games/Arch_Amazon-GameLift_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Connect', 'Business Applications', 'business_applications/Arch_Amazon-Connect_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon WorkDocs', 'Business Applications', 'business_applications/Arch_Amazon-WorkDocs_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Pinpoint', 'Business Applications', 'business_applications/Arch_Amazon-Pinpoint_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Chime', 'Business Applications', 'business_applications/Arch_Amazon-Chime_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Chime SDK', 'Business Applications', 'business_applications/Arch_Amazon-Chime-SDK_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Alexa For Business', 'Business Applications', 'business_applications/Arch_Alexa-For-Business_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon WorkMail', 'Business Applications', 'business_applications/Arch_Amazon-WorkMail_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Supply Chain', 'Business Applications', 'business_applications/Arch_AWS-Supply-Chain_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Wickr', 'Business Applications', 'business_applications/Arch_AWS-Wickr_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Simple Email Service', 'Business Applications', 'business_applications/Arch_Amazon-Simple-Email-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Honeycode', 'Business Applications', 'business_applications/Arch_Amazon-Honeycode_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Reserved Instance Reporting', 'Cloud Financial Management', 'cloud_financial_management/Arch_Reserved-Instance-Reporting_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Savings Plans', 'Cloud Financial Management', 'cloud_financial_management/Arch_Savings-Plans_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Billing Conductor', 'Cloud Financial Management', 'cloud_financial_management/Arch_AWS-Billing-Conductor_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Cost Profiler', 'Cloud Financial Management', 'cloud_financial_management/Arch_AWS-Application-Cost-Profiler_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Budgets', 'Cloud Financial Management', 'cloud_financial_management/Arch_AWS-Budgets_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cost and Usage Report', 'Cloud Financial Management', 'cloud_financial_management/Arch_AWS-Cost-and-Usage-Report_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Cost Explorer', 'Cloud Financial Management', 'cloud_financial_management/Arch_AWS-Cost-Explorer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Mainframe Modernization', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Mainframe-Modernization_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS DataSync', 'Migration / Transfer', 'migration_transfer/Arch_AWS-DataSync_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Migration Hub', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Migration-Hub_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Migration Evaluator', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Migration-Evaluator_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Transfer Family', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Transfer-Family_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Discovery Service', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Application-Discovery-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Application Migration Service', 'Migration / Transfer', 'migration_transfer/Arch_AWS-Application-Migration-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon HealthLake', 'Machine Learning', 'machine_learning/Arch_Amazon-HealthLake_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Deep Learning Containers', 'Machine Learning', 'machine_learning/Arch_AWS-Deep-Learning-Containers_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon SageMaker Studio Lab', 'Machine Learning', 'machine_learning/Arch_Amazon-SageMaker-Studio-Lab_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lookout for Vision', 'Machine Learning', 'machine_learning/Arch_Amazon-Lookout-for-Vision_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Neuron', 'Machine Learning', 'machine_learning/Arch_AWS-Neuron_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Textract', 'Machine Learning', 'machine_learning/Arch_Amazon-Textract_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('TensorFlow on AWS', 'Machine Learning', 'machine_learning/Arch_TensorFlow-on-AWS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS DeepComposer', 'Machine Learning', 'machine_learning/Arch_AWS-DeepComposer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lookout for Metrics', 'Machine Learning', 'machine_learning/Arch_Amazon-Lookout-for-Metrics_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CodeGuru', 'Machine Learning', 'machine_learning/Arch_Amazon-CodeGuru_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Comprehend Medical', 'Machine Learning', 'machine_learning/Arch_Amazon-Comprehend-Medical_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Deep Learning AMIs', 'Machine Learning', 'machine_learning/Arch_AWS-Deep-Learning-AMIs_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Augmented AI A2I', 'Machine Learning', 'machine_learning/Arch_Amazon-Augmented-AI-A2I_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon SageMaker Ground Truth', 'Machine Learning', 'machine_learning/Arch_Amazon-SageMaker-Ground-Truth_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Personalize', 'Machine Learning', 'machine_learning/Arch_Amazon-Personalize_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Monitron', 'Machine Learning', 'machine_learning/Arch_Amazon-Monitron_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lookout for Equipment', 'Machine Learning', 'machine_learning/Arch_Amazon-Lookout-for-Equipment_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Omics', 'Machine Learning', 'machine_learning/Arch_Amazon-Omics_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS DeepLens', 'Machine Learning', 'machine_learning/Arch_AWS-DeepLens_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Rekognition', 'Machine Learning', 'machine_learning/Arch_Amazon-Rekognition_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Forecast', 'Machine Learning', 'machine_learning/Arch_Amazon-Forecast_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Apache MXNet on AWS', 'Machine Learning', 'machine_learning/Arch_Apache-MXNet-on-AWS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Fraud Detector', 'Machine Learning', 'machine_learning/Arch_Amazon-Fraud-Detector_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon DevOps Guru', 'Machine Learning', 'machine_learning/Arch_Amazon-DevOps-Guru_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon SageMaker', 'Machine Learning', 'machine_learning/Arch_Amazon-SageMaker_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Elastic Inference', 'Machine Learning', 'machine_learning/Arch_Amazon-Elastic-Inference_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Kendra', 'Machine Learning', 'machine_learning/Arch_Amazon-Kendra_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Transcribe', 'Machine Learning', 'machine_learning/Arch_Amazon-Transcribe_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('TorchServe', 'Machine Learning', 'machine_learning/Arch_TorchServe_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Comprehend', 'Machine Learning', 'machine_learning/Arch_Amazon-Comprehend_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon CodeWhisperer', 'Machine Learning', 'machine_learning/Arch_Amazon-CodeWhisperer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Polly', 'Machine Learning', 'machine_learning/Arch_Amazon-Polly_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Lex', 'Machine Learning', 'machine_learning/Arch_Amazon-Lex_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Panorama', 'Machine Learning', 'machine_learning/Arch_AWS-Panorama_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS DeepRacer', 'Machine Learning', 'machine_learning/Arch_AWS-DeepRacer_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Translate', 'Machine Learning', 'machine_learning/Arch_Amazon-Translate_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Location Service', 'Frontend / Mobile', 'frontend_mobile/Arch_Amazon-Location-Service_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Device Farm', 'Frontend / Mobile', 'frontend_mobile/Arch_AWS-Device-Farm_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Amplify', 'Frontend / Mobile', 'frontend_mobile/Arch_AWS-Amplify_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Button', 'IoT', 'iot/Arch_AWS-IoT-Button_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Analytics', 'IoT', 'iot/Arch_AWS-IoT-Analytics_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Greengrass', 'IoT', 'iot/Arch_AWS-IoT-Greengrass_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('FreeRTOS', 'IoT', 'iot/Arch_FreeRTOS_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT RoboRunner', 'IoT', 'iot/Arch_AWS-IoT-RoboRunner_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Events', 'IoT', 'iot/Arch_AWS-IoT-Events_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Things Graph', 'IoT', 'iot/Arch_AWS-IoT-Things-Graph_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT TwinMaker', 'IoT', 'iot/Arch_AWS-IoT-TwinMaker_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Device Management', 'IoT', 'iot/Arch_AWS-IoT-Device-Management_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Device Defender', 'IoT', 'iot/Arch_AWS-IoT-Device-Defender_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT SiteWise', 'IoT', 'iot/Arch_AWS-IoT-SiteWise_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT ExpressLink', 'IoT', 'iot/Arch_AWS-IoT-ExpressLink_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT EduKit', 'IoT', 'iot/Arch_AWS-IoT-EduKit_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT 1 Click', 'IoT', 'iot/Arch_AWS-IoT-1-Click_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT Core', 'IoT', 'iot/Arch_AWS-IoT-Core_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IoT FleetWise', 'IoT', 'iot/Arch_AWS-IoT-FleetWise_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS RoboMaker', 'Robotics', 'robotics/Arch_AWS-RoboMaker_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Training Certification', 'Customer Enablement', 'customer_enablement/Arch_AWS-Training-Certification_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Professional Services', 'Customer Enablement', 'customer_enablement/Arch_AWS-Professional-Services_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS IQ', 'Customer Enablement', 'customer_enablement/Arch_AWS-IQ_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Managed Services', 'Customer Enablement', 'customer_enablement/Arch_AWS-Managed-Services_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Support', 'Customer Enablement', 'customer_enablement/Arch_AWS-Support_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS re', 'Customer Enablement', 'customer_enablement/Arch_AWS-re_Post_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Activate', 'Customer Enablement', 'customer_enablement/Arch_AWS-Activate_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon AppStream', 'End User Computing', 'end_user_computing/Arch_Amazon-AppStream_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon WorkLink', 'End User Computing', 'end_user_computing/Arch_Amazon-WorkLink_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon WorkSpaces Family', 'End User Computing', 'end_user_computing/Arch_Amazon-WorkSpaces-Family_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('AWS Ground Station', 'Satellite', 'satellite/Arch_AWS-Ground-Station_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Quantum Ledger Database', 'Blockchain', 'blockchain/Arch_Amazon-Quantum-Ledger-Database_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Managed Blockchain', 'Blockchain', 'blockchain/Arch_Amazon-Managed-Blockchain_64@5x.png');
INSERT INTO icons (name, category, object_key) VALUES ('Amazon Braket', 'Quantum Technologies', 'quantum_technologies/Arch_Amazon-Braket_64@5x.png');